### ISSUE TITLE
EditPad displays Tlwg * Medium and Bold as Bold

### ISSUE THREAD

**Issue by alysdexia** [tlwg/fonts-tlwg#5]
NotePad displays them correctly.

**Comment by abhabongse** [comment]
Do you have a minimal code to illustrate what you mean?

**Comment by alysdexia** [comment]
No code.  Download [EditPad Lite](https://www.editpadlite.com/download.html) then view these styles in the Font... panel.

**Comment by thep** [comment]
Would you mind checking two groups of other fonts whether the same behavior happens to them?

- Group 1: Purisa, Sawasdee, Umpush, Waree, Garuda, Norasi, and Loma
- Group 2: Kinnari

I just want to confirm a hypothesis on how EditPad decides whether a font is bold. Thank you.

**Comment by alysdexia** [comment]
Umpush Light displays as Medium and Kinnari Medium displays as Bold.

**Comment by thep** [comment]
And no problem with other Group 1 fonts, right? If so, that means EditPlus decides weight based on TTFWeight proprerty. But I'm a bit surprised to hear that Umpush Light is classified as Medium, because it already uses 300 "Light", according to MS spec:

https://www.microsoft.com/typography/otspec/os2.htm#wtc

**Comment by thep** [comment]
Please try the modified TlwgTypo font as attached.

[TlwgTypo.zip](https://github.com/tlwg/fonts-tlwg/files/1596210/TlwgTypo.zip)
